src/Web/Pages/CheepBox.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Core;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace Web.Pages;

/// <summary>
/// The page model for the cheep-box partial, which allows the user to send cheeps(via the Share endpoint)
/// </summary>
/// <param name="service">Our Service, injected via DI</param>
/// <param name="userManager">The Usermanager. Also injected by Asp.Net</param>
/// <param name="User">The Current user, needed to check whether the user is authenticated. Also injected by Asp.Net</param>
public class CheepBoxModel(ICheepService service, UserManager<Author> userManager, System.Security.Claims.ClaimsPrincipal User)
{
    public Author? Author { get; set; }
    
    public async Task OnPostShareAsync(string Message) {
        if (User.Identity != null && !User.Identity.IsAuthenticated)
        {
            return ;
        }
        
        // simply truncate the message if too long
        if (Message.Length > 160) { Message = Message.Substring(0, 160); }

        // Create the new Cheep 

        // Save the new Cheep (assuming a SaveCheepAsync method exists in your service or repository)
        await service.SendCheep((await userManager.GetUserAsync(User)).UserName, Message, DateTime.UtcNow);
        return;
    }
}

src/Web/Pages/Follow.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Core;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace Web.Pages;

/// <summary>
/// The Following page model, which is the page model for the author partial. 
/// Supports the follow endpoint, which allows an authenticated user to follow or unfollow other authors
/// </summary>
/// <param name="service">Our service, injected.</param>
/// <param name="userManager">The usermanager, needed to fetch the current users username.</param>
/// <param name="User">The current user, needed to check whether he is authenticated.</param>
public class FollowModel(ICheepService service, UserManager<Author> userManager, System.Security.Claims.ClaimsPrincipal User)
{
    public async Task OnPostFollowAsync(string UsrnmToFollow) {
        if (UsrnmToFollow == null ||(User.Identity != null && !User.Identity.IsAuthenticated))
        {
            return;
        }

        Author curUser = await userManager!.GetUserAsync(User!);

        await service.AddOrRemoveFollower(curUser.UserName ?? throw new Exception("Wtf user with null username"), UsrnmToFollow); 
        return;
    }
}

src/Web/Pages/Shared/ChangePage.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Core;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Infrastructure.Migrations;
using System.Text.Json;
using System.IO.Compression;
using Microsoft.AspNetCore.Authentication;
using System.Text;

namespace Web.Pages;

[Authorize]
public class ChangePageModel : PageModel
{
    private readonly ICheepService _cheepService; 
    private readonly UserManager<Author> _userManager;

    public ChangePageModel(ICheepService cheepService, UserManager<Author> userManager)
    {
        _cheepService = cheepService;
        _userManager = userManager;
    }

    public int CurrentPage { get; set; } = 1;

    public int MaxCheeps { get; set; } = 32; 

    public int TotalCheeps {get; set;} 

    public IEnumerable<CheepDTO> Cheeps { get; set; } = new List<CheepDTO>();
    [Required]
    public string Direction { get; set; }


    public async Task<IActionResult> OnGetChangePageAsync(string Direction, int currentPage = 1) {
        

        TotalCheeps = _cheepService.GetTotalCheepsAccount();
       
        if (Direction == "Previous" && currentPage > 1) 
        {
            CurrentPage = currentPage - 1;  // go to previous page
        } 
        else if(Direction == "Next" && currentPage * MaxCheeps < TotalCheeps)
        {
             CurrentPage = currentPage + 1; // go to next page
        } 
        else
        {
            CurrentPage = currentPage; // stay on the same page
        }
       
    
        Cheeps = await _cheepService.GetCheepsAsync(CurrentPage); 

        return Page();

    }
}

src/Web/Pages/Shared/_AuthorPartial.cshtml
@inject SignInManager<Core.Author> SignInManager
@inject UserManager<Core.Author> UserManager
@using Core
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@* A simple partial class that displays an authors name as well as follow/unfollow buttons if the current user is logged in *@

@{
    var currentUser = await UserManager.GetUserAsync(User);
}

@* we pass the cheepDTO here *@
@model CheepDTO; 

<p>
    <strong>
        <a href="/@Model.AuthorName">@Model.AuthorName</a>
    </strong>
    @if (SignInManager.IsSignedIn(User) && currentUser != null && currentUser.UserName != @Model.AuthorName)
    {
    <form method="post" asp-page-handler="Follow">
    <input type="hidden" name="UsrnmToFollow" value="@Model.AuthorName" />
    <button type="submit" class="btn btn-primary follow-btn-position follow-btn-size">
        @if (currentUser.FollowsAuthor(@Model.AuthorName))
                {
                <span>Unfollow</span>
                }
                else
                {
                <span>Follow</span>
                }
        </button>
    </form>
    }
</p>

src/Web/Pages/Shared/_ChangePage.cshtml
@inject SignInManager<Core.Author> SignInManager 
@inject UserManager<Core.Author> UserManager
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@if (SignInManager.IsSignedIn(User))
{
    <section>
        <form method="get" asp-page-handler="ChangePage">
        <input type="hidden" name="currentPage" value="@Model.CurrentPage" />
        <button type="submit" class="change-page-btns btn-primary" name= "direction" value="Previous" @(Model.CurrentPage == 1 ? "disabled" : "")>Previous page</button>
        <button type="submit" class="change-page-btns btn-primary" name= "direction" value="Next" @(Model.CurrentPage * Model.MaxCheeps >= Model.TotalCheeps ? "disabled" : "")>Next page</button>
        </form> 
    </section>
  
}

src/Web/Pages/Shared/_CheepBox.cshtml
@inject SignInManager<Core.Author> SignInManager 
@inject UserManager<Core.Author> UserManager
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@* Partial for the form to send cheeps, only displayed for logged in authors *@

@model string

@if (SignInManager.IsSignedIn(User))
{
    <div class="cheepbox">
    <h3>What's on your mind, @Model</h3>
    <form method="post" asp-page-handler="Share">
        <input type="text" name="Message" required>
        <input type="submit" value="Share">
    </form>
    </div>
}

src/Web/Pages/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@* The top level layout which includes a navigation bar(somewhat confusingly named _LoginPartial) *@

<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <link href="/css/style.css" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="/favicon/favicon.ico">
</head>
<body>
<div class=page>

    <h1><img src="/images/icon1.png" alt="Icon1"/>Chirp!</h1>

    <header>

        <partial name="_LoginPartial"/>
     </header>

    <div class=body>
            @RenderBody()
    </div>
    
    <div class=footer>
        Chirp &mdash; An ASP.NET Application
    </div>

</div>
</body>
@await RenderSectionAsync("Scripts", required: false)
</html>